// VDF Prompt Library Data
const promptsData = {
    "phases": [
        {
            "id": "strategy",
            "name": "Strategy",
            "description": "Establish vision, set objectives, and align with organisational goals",
            "color": "#b794f6",
            "icon": '<i data-feather="target" style="color: #ff0000; stroke-width: 1.5px;"></i>',
            "prompts": [
                {
                    "id": "okr-development",
                    "title": "OKR Development Assistant",
                    "description": "Create quarterly OKRs aligned with Medibank's mission and Hub objectives",
                    "complexity": "medium",
                    "timeEstimate": "15-30 mins",
                    "roles": ["Squad Lead", "Product Manager", "Hub Lead"],
                    "tags": ["OKRs", "Planning", "Alignment"],
                    "prompt": "Help me develop quarterly OKRs for our {{squad_name}} squad that align with {{hub_objectives}}. For each proposed objective, suggest 3-4 key results that are: measurable within our quarterly timeframe, directly influenced by our squad's capabilities, and clearly connected to customer value. Include potential leading indicators we can track weekly.",
                    "variables": ["squad_name", "hub_objectives"],
                    "rating": 4.8,
                    "usageCount": 156
                },
                {
                    "id": "vision-alignment",
                    "title": "Mission Alignment Analyser",
                    "description": "Connect squad work to Medibank's 'Better health for all Australians' mission",
                    "complexity": "low",
                    "timeEstimate": "10-15 mins",
                    "roles": ["Squad Lead", "Product Manager"],
                    "tags": ["Vision", "Mission", "Alignment"],
                    "prompt": "As a {{hub_name}} squad working on {{initiative_description}}, analyse how our proposed work directly contributes to improving health outcomes for Australians. Identify three specific ways our deliverables will create measurable health value, considering both immediate user benefits and broader systemic impacts.",
                    "variables": ["hub_name", "initiative_description"],
                    "rating": 4.6,
                    "usageCount": 89
                },
                {
                    "id": "pre-mortem-risk-assessment",
                    "title": "Pre-mortem Risk Assessment",
                    "description": "Use this prompt during the strategy or shaping phase to critically identify potential failure points for an initiative",
                    "complexity": "high",
                    "timeEstimate": "30-45 mins",
                    "roles": ["Squad Lead", "Engineering Lead"],
                    "tags": ["Risk Assessment", "Strategy", "Planning"],
                    "prompt": "Let's conduct a pre-mortem for {{initiative_description}}. Pretend it's the end of the project and it failed to meet {{key_objectives}}. Brainstorm the reasons for this failure – especially consider if our assumptions ({{key_assumptions}}) turned out to be false – examining aspects such as:\nStrategy (e.g., misaligned goals or shifting market conditions)\nExecution (e.g., technical hurdles, resource constraints, process breakdowns)\nUser Impact (e.g., poor user adoption or negative feedback)\nExternal Factors (e.g., regulatory changes or new competitors)\nFor each identified reason, suggest proactive steps we can take now to prevent or mitigate it. Structure the output as:\nPotential Failure Reason: [Description of issue]\nMitigation: [How to address or prevent this issue]\nProvide multiple distinct reasons and mitigations, ensuring they cover different dimensions of the project.",
                    "variables": ["initiative_description", "key_objectives", "key_assumptions"],
                    "rating": 4.9,
                    "usageCount": 0
                },
                {
                    "id": "stakeholder-alignment-brief",
                    "title": "Stakeholder Alignment Brief",
                    "description": "Use in the strategy phase to align multiple stakeholders on a project's vision and plan",
                    "complexity": "medium",
                    "timeEstimate": "25-35 mins",
                    "roles": ["Squad Lead", "Product Manager"],
                    "tags": ["Stakeholders", "Alignment", "Communication"],
                    "prompt": "Help me prepare a brief to align all stakeholders for {{project_vision}}. The stakeholders include {{key_stakeholders}}, and our company's strategic objectives are {{company_objectives}}. Some known concerns or differing priorities among these stakeholders are: {{stakeholder_concerns}}. Please draft a clear and concise alignment document that includes:\nProject Overview: A summary of the project vision and how it supports our company objectives.\nStakeholder Interests: Acknowledge each stakeholder's goals or concerns and show how the project addresses them (or propose compromises where needed).\nValue Proposition: Explain the value and impact of this initiative for the business and customers, highlighting why it matters.\nNext Steps & Responsibilities: Outline the agreed next steps and who is responsible for each.\nThe tone should be inclusive and authoritative, anticipating possible objections and addressing them. Ensure the brief demonstrates how {{project_vision}} is a shared win for all stakeholders and aligns with {{company_objectives}}.",
                    "variables": ["project_vision", "key_stakeholders", "company_objectives", "stakeholder_concerns"],
                    "rating": 4.8,
                    "usageCount": 0
                },
                {
                    "id": "future-back-scenario-planner",
                    "title": "Future-Back Scenario Planner",
                    "description": "Craft a vivid, testable vision of the world in five years and back-cast strategic moves.",
                    "complexity": "high",
                    "timeEstimate": "45-60 mins",
                    "roles": ["Hub Lead", "Product Manager", "Executive Sponsor"],
                    "tags": ["Scenario Planning", "Strategic Foresight", "Back-casting"],
                    "prompt": "Using the end-state {{END_DATE}}, write a one-page 'World in {{END_DATE}}' memo (see Eric Schmidt framework). List 10 bold but testable predictions with confidence levels, leading indicators, and kill-switch thresholds. Rank them by Impact × Confidence × Strategic Fit, flagging one-way vs two-way doors. Finish with a three-sentence Focus Thesis that clarifies where we will and will not invest.",
                    "variables": ["END_DATE"],
                    "rating": 0,
                    "usageCount": 0
                },
                {
                    "id": "assumption-inversion-challenge",
                    "title": "Assumption-Inversion Challenge",
                    "description": "Flip core beliefs upside-down to expose blind spots and strategic risk.",
                    "complexity": "medium",
                    "timeEstimate": "25-35 mins",
                    "roles": ["Squad Lead", "Product Manager", "Business Analyst"],
                    "tags": ["Inversion Thinking", "Risk", "Critical Inquiry"],
                    "prompt": "List our top 5 strategic assumptions for {{initiative_name}}. Invert each (e.g., assume the opposite is true). For every inversion: a) describe the worst-case outcome if we are wrong, b) identify early warning signals, c) design one preventive action or contingency plan.",
                    "variables": ["initiative_name"],
                    "rating": 0,
                    "usageCount": 0
                }
            ]
        },
        {
            "id": "shaping",
            "name": "Shaping",
            "description": "Evaluate ideas for desirability, viability, and feasibility",
            "color": "#f6ad55",
            "icon": '<i data-feather="zap" style="color: #ff0000; stroke-width: 1.5px;"></i>',
            "prompts": [
                {
                    "id": "dvf-evaluation",
                    "title": "Desirability-Viability-Feasibility Evaluator",
                    "description": "Systematic analysis of idea potential across DVF dimensions",
                    "complexity": "high",
                    "timeEstimate": "30-45 mins",
                    "roles": ["Product Manager", "Squad Lead", "Engineering Lead"],
                    "tags": ["DVF", "Evaluation", "Decision Making"],
                    "prompt": "Evaluate {{idea_description}} across desirability, viability, and feasibility dimensions. For Desirability: What customer pain points does this address? What evidence supports customer demand? For Viability: How does this align with business objectives? What's the expected ROI? For Feasibility: What technical constraints exist? What resources are required? Provide a confidence score (1-10) for each dimension with detailed reasoning.",
                    "variables": ["idea_description"],
                    "rating": 4.9,
                    "usageCount": 203
                },
                {
                    "id": "risk-assessment",
                    "title": "Technical Risk Profiler",
                    "description": "Identify and assess technical and operational risks",
                    "complexity": "medium",
                    "timeEstimate": "20-30 mins",
                    "roles": ["Engineering Lead", "Squad Lead"],
                    "tags": ["Risk", "Technical", "Assessment"],
                    "prompt": "Analyse potential risks for {{solution_description}}. Identify: critical technical dependencies, required new capabilities, integration complexity with existing systems, timeline implications, and major risk factors. For each risk, suggest mitigation strategies and rate probability/impact. Provide overall risk score.",
                    "variables": ["solution_description"],
                    "rating": 4.5,
                    "usageCount": 127
                },
                {
                    "id": "rapid-validation",
                    "title": "Lightning Validation Designer",
                    "description": "Design quick validation experiments for early concept testing",
                    "complexity": "medium",
                    "timeEstimate": "15-25 mins",
                    "roles": ["Product Manager", "UX Designer"],
                    "tags": ["Validation", "Testing", "Experiments"],
                    "prompt": "Design a 1-week validation experiment for {{concept_description}}. Include: hypothesis to test, success metrics, experiment design, required resources, and expected learnings. Focus on fastest way to gather meaningful customer feedback.",
                    "variables": ["concept_description"],
                    "rating": 4.4,
                    "usageCount": 98
                },
                {
                    "id": "feature-impact-mapping",
                    "title": "Feature Impact Mapping Assistant",
                    "description": "Use during the shaping phase when defining a new feature or initiative",
                    "complexity": "high",
                    "timeEstimate": "30-45 mins",
                    "roles": ["Product Manager", "Business Analyst"],
                    "tags": ["Impact Mapping", "Feature Definition", "Value Delivery"],
                    "prompt": "I'm working on defining {{feature_description}}. The goal is {{desired_outcome}}. Let's perform an impact mapping exercise:\nGoal: Confirm the high-level outcome or business goal ({{desired_outcome}}) that this feature aims to achieve.\nActors: Identify who will be impacted or can influence the outcome (e.g., {{primary_actors}}, and any other user segments or stakeholders).\nImpacts: For each actor, list the desired changes in behaviour or outcomes that {{feature_description}} should drive to reach the goal. Think critically about how their actions or experiences would change.\nDeliverables: Finally, list the specific deliverables or feature components we will build in {{feature_description}} that lead to those impacts.\nPresent the results in a structured format (Goal → Actors → Impacts → Deliverables). Highlight any assumptions linking these elements and note any potential side effects or unintended consequences. Ensure the mapping shows a clear logic from the feature to the outcome.",
                    "variables": ["feature_description", "desired_outcome", "primary_actors"],
                    "rating": 4.7,
                    "usageCount": 0
                },
                {
                    "id": "technical-solution-evaluator",
                    "title": "Technical Solution Evaluator",
                    "description": "Use in the shaping or early design phase to evaluate multiple technical implementation options",
                    "complexity": "high",
                    "timeEstimate": "45-60 mins",
                    "roles": ["Engineering Lead", "Product Manager"],
                    "tags": ["Technical Evaluation", "Decision Making", "Architecture"],
                    "prompt": "We need to decide on an implementation approach for {{problem_statement}}. The options under consideration are: {{solution_options}}. Our decision criteria include {{decision_criteria}}. Please evaluate each option against these criteria:\nOption Overview: Briefly describe how the solution works or what it entails.\nPros: List the benefits and strengths (e.g., meets certain criteria well, simplicity, performance advantages, familiarity to the team).\nCons: List the drawbacks or risks (e.g., criteria where it falls short, complexity, potential high costs, new unknowns introduced).\nSystem Impact: Explain how this option would affect our existing systems or processes (for example, new dependencies, changes to user experience, impacts on other teams or infrastructure).\nLong-Term Considerations: Discuss future implications like scalability, maintainability, and alignment with our long-term strategy or tech stack.\nRecommendation: Based on the above, suggest which option is the best choice and why (or if further investigation is needed before deciding).\nEnsure the analysis remains objective and questions any assumptions. The output should clearly compare trade-offs and show how each option measures up against {{decision_criteria}}.",
                    "variables": ["problem_statement", "solution_options", "decision_criteria"],
                    "rating": 4.8,
                    "usageCount": 0
                },
                {
                    "id": "systems-thinking-impact-loop",
                    "title": "Systems-Thinking Impact Loop",
                    "description": "Map reinforcing and balancing loops to reveal second-order effects before committing.",
                    "complexity": "high",
                    "timeEstimate": "45-60 mins",
                    "roles": ["Product Manager", "Business Analyst", "Engineering Lead"],
                    "tags": ["Systems Thinking", "Causal Loops", "Complexity"],
                    "prompt": "Draw a causal-loop diagram for {{idea_description}} covering users, tech, policy, and market factors. Identify at least two reinforcing and two balancing loops. For each loop, discuss potential unintended consequences and mitigation experiments.",
                    "variables": ["idea_description"],
                    "rating": 0,
                    "usageCount": 0
                },
                {
                    "id": "second-order-consequence-mapper",
                    "title": "Second-Order Consequence Mapper",
                    "description": "Stress-test proposed features by tracing ripple effects three steps out.",
                    "complexity": "medium",
                    "timeEstimate": "30-40 mins",
                    "roles": ["Product Manager", "UX Designer", "Squad Lead"],
                    "tags": ["Second-Order Thinking", "Decision Quality"],
                    "prompt": "For each key decision in {{feature_description}}, list first-order benefits and costs. Then map second and third-order consequences across customer, team, compliance, and sustainability dimensions. Highlight surprises and choose one insight to refine the feature.",
                    "variables": ["feature_description"],
                    "rating": 0,
                    "usageCount": 0
                }
            ]
        },
        {
            "id": "discovery",
            "name": "Discovery",
            "description": "Deep dive into requirements and solution architecture",
            "color": "#68d391",
            "icon": '<i data-feather="search" style="color: #ff0000; stroke-width: 1.5px;"></i>',
            "prompts": [
                {
                    "id": "requirements-elicitation",
                    "title": "Requirements Synthesis Engine",
                    "description": "Transform user research into actionable technical requirements",
                    "complexity": "high",
                    "timeEstimate": "45-60 mins",
                    "roles": ["Product Manager", "Business Analyst", "Engineering Lead"],
                    "tags": ["Requirements", "Analysis", "Documentation"],
                    "prompt": "Based on user research findings {{research_summary}}, generate comprehensive requirements for {{feature_description}}. Include: functional requirements organised by user journey, non-functional requirements (performance, security, scalability), integration requirements with existing systems, and acceptance criteria. Organise by MoSCoW priority.",
                    "variables": ["research_summary", "feature_description"],
                    "rating": 4.7,
                    "usageCount": 189
                },
                {
                    "id": "solution-architecture",
                    "title": "Architecture Explorer",
                    "description": "Design solution architecture with enterprise integration mapping",
                    "complexity": "high",
                    "timeEstimate": "60-90 mins",
                    "roles": ["Engineering Lead", "Enterprise Architect"],
                    "tags": ["Architecture", "Integration", "Design"],
                    "prompt": "Design solution architecture for {{problem_statement}}. Consider: integration points with existing Medibank systems, scalable design patterns, technology choices aligned with our roadmap, non-functional requirements, and potential technical debt. Present 2-3 alternative approaches with trade-off analysis.",
                    "variables": ["problem_statement"],
                    "rating": 4.8,
                    "usageCount": 145
                },
                {
                    "id": "user-research-planner",
                    "title": "User Research Planner",
                    "description": "Use in the discovery phase to design a user research plan",
                    "complexity": "medium",
                    "timeEstimate": "25-35 mins",
                    "roles": ["UX Designer", "Product Manager"],
                    "tags": ["User Research", "Discovery", "Planning"],
                    "prompt": "I need to plan a user research study to achieve the goal: {{research_goal}}. The target users are {{target_user_group}}. Given {{constraints}}, please outline a research plan that includes:\nResearch Objectives: 3-5 key questions we aim to answer or hypotheses to validate about {{research_goal}}.\nMethodology: Recommended research methods (e.g., interviews, surveys, usability tests, field observations) and why each is suitable for our goals and constraints.\nKey Questions/Tasks: A brief discussion guide or list of tasks for participants, designed to elicit insights related to our objectives.\nBias Mitigation: Potential biases or validity threats (e.g., leading questions, sampling bias) and how we'll address them to ensure reliable results.\nTimeline & Logistics: A rough timeline for recruiting {{target_user_group}}, conducting the study, and analysing results, considering {{constraints}}.\nMake sure the plan is thorough but realistic, and explain how each part of the plan will help us learn about {{research_goal}}. The output should be structured for easy review by the team.",
                    "variables": ["research_goal", "target_user_group", "constraints"],
                    "rating": 4.6,
                    "usageCount": 0
                },
                {
                    "id": "lateral-thinking-ideation-jam",
                    "title": "Lateral-Thinking Ideation Jam",
                    "description": "Unlock unconventional solutions by provocation, random entry and analogy.",
                    "complexity": "medium",
                    "timeEstimate": "25-35 mins",
                    "roles": ["UX Designer", "Product Manager", "Squad Lead"],
                    "tags": ["Lateral Thinking", "Creative Ideation"],
                    "prompt": "State the problem {{problem_statement}}. Apply three techniques: a) Provocation—write a deliberately outrageous statement and force-fit three ideas; b) Random Entry—grab a random noun and generate three analogies; c) Reversal—describe the opposite solution. Capture nine raw ideas and cluster them into themes.",
                    "variables": ["problem_statement"],
                    "rating": 0,
                    "usageCount": 0
                },
                {
                    "id": "red-team-devils-advocate",
                    "title": "Red-Team Devil's Advocate",
                    "description": "Pressure-test discovery insights by simulating a hostile critic.",
                    "complexity": "high",
                    "timeEstimate": "40-50 mins",
                    "roles": ["Business Analyst", "Scrum Master", "Engineering Lead"],
                    "tags": ["Red Teaming", "Devil's Advocate", "Bias Busting"],
                    "prompt": "Split participants into Builders and Red Team for {{solution_concept}}. Builders present value prop, evidence, and key assumptions. Red Team has 15 minutes to craft three high-impact critiques (feasibility, viability, desirability). Builders then propose counter-actions or pivots. Rotate roles and repeat.",
                    "variables": ["solution_concept"],
                    "rating": 0,
                    "usageCount": 0
                }
            ]
        },
        {
            "id": "delivery",
            "name": "Design & Delivery",
            "description": "Execute solutions with quality and iterative delivery",
            "color": "#63b3ed",
            "icon": '<i data-feather="package" style="color: #ff0000; stroke-width: 1.5px;"></i>',
            "prompts": [
                {
                    "id": "sprint-planning",
                    "title": "Sprint Breakdown Assistant",
                    "description": "Break epics into deliverable user stories with clear acceptance criteria",
                    "complexity": "medium",
                    "timeEstimate": "30-45 mins",
                    "roles": ["Product Manager", "Squad Lead", "Scrum Master"],
                    "tags": ["Sprint Planning", "User Stories", "Agile"],
                    "prompt": "Break down {{epic_description}} into sprint-sized user stories that: deliver incremental value, can be completed in 2-week sprints, include clear acceptance criteria, and consider technical dependencies. For each story, estimate story points, define done criteria, and suggest testing approach.",
                    "variables": ["epic_description"],
                    "rating": 4.8,
                    "usageCount": 267
                },
                {
                    "id": "quality-assurance",
                    "title": "QA Strategy Designer",
                    "description": "Comprehensive testing strategy across functional and non-functional requirements",
                    "complexity": "high",
                    "timeEstimate": "35-50 mins",
                    "roles": ["QA Lead", "Engineering Lead"],
                    "tags": ["Testing", "Quality", "Strategy"],
                    "prompt": "Design testing strategy for {{solution_description}} covering: functional testing scenarios, performance/load testing, security testing, integration testing, user acceptance testing, and accessibility compliance. Organise by testing phase and suggest tools from Medibank's tech stack.",
                    "variables": ["solution_description"],
                    "rating": 4.7,
                    "usageCount": 178
                },
                {
                    "id": "deployment-planning",
                    "title": "Deployment Risk Analyzer",
                    "description": "Plan deployment strategy with risk mitigation and rollback procedures",
                    "complexity": "medium",
                    "timeEstimate": "20-30 mins",
                    "roles": ["Engineering Lead", "DevOps Engineer"],
                    "tags": ["Deployment", "Risk", "Operations"],
                    "prompt": "Plan deployment strategy for {{feature_name}} considering: rollout phases, monitoring requirements, rollback procedures, communication plan, and success criteria. Include specific checkpoints and escalation procedures.",
                    "variables": ["feature_name"],
                    "rating": 4.5,
                    "usageCount": 134
                },
                {
                    "id": "design-critique-preparation",
                    "title": "Design Critique Preparation",
                    "description": "Use during the design & delivery phase to prepare for a design critique session",
                    "complexity": "medium",
                    "timeEstimate": "20-30 mins",
                    "roles": ["UX Designer", "Product Manager"],
                    "tags": ["Design Critique", "UX", "Feedback"],
                    "prompt": "I'm preparing for a critique of our design for {{design_concept}}. We need to evaluate it against our goals and user needs. Key scenarios include {{key_user_scenarios}}, and our design aims to achieve {{design_goals}}. Help me outline a structured critique plan with guiding questions:\nUsability & Accessibility: How easily can users accomplish key tasks (e.g., {{key_user_scenarios}})? Are there any points of confusion or potential accessibility barriers?\nVisual Design & Content: Does the visual style and content align with our brand and clearly communicate to users? Are there areas that seem cluttered, inconsistent, or unclear?\nEdge Cases & Errors: What happens in uncommon scenarios or if something goes wrong? Identify a few edge cases or error conditions in {{design_concept}} and questions to ensure the design handles them gracefully.\nTechnical Feasibility: Could any part of the design be difficult or costly to implement? Flag components that might have performance or complexity concerns, so we can verify them with engineering.\nConsistency & Integration: Does {{design_concept}} fit well with our existing product experience? Are we reusing established UI patterns and components, or introducing new ones that need validation?\nPlease format the output as a list of these sections with bullet points or questions under each. The goal is to thoroughly critique {{design_concept}} from multiple angles and uncover any issues or improvements before development.",
                    "variables": ["design_concept", "key_user_scenarios", "design_goals"],
                    "rating": 4.7,
                    "usageCount": 0
                },
                {
                    "id": "test-plan-strategizer",
                    "title": "Test Plan Strategizer",
                    "description": "Use during the design & delivery phase, before a major release or feature rollout",
                    "complexity": "high",
                    "timeEstimate": "30-45 mins",
                    "roles": ["QA Lead", "Engineering Lead"],
                    "tags": ["Testing", "Strategy", "Quality Assurance"],
                    "prompt": "I'm creating a test strategy for {{feature_description}}. We know some high-risk areas include {{risk_areas}}. Help outline a thorough test plan:\nScope of Testing: Identify the main functionalities and user flows in {{feature_description}} that need to be tested. Emphasise any areas critical to success or prone to failure, especially those related to {{risk_areas}}.\nTest Types & Coverage: For each area of scope, recommend the types of tests needed (unit, integration, end-to-end, performance, security, etc.) and ensure we cover both typical scenarios and edge cases.\nPrioritisation: Based on the risks, which tests or scenarios should be highest priority? Highlight what must pass before release (focus on areas involving {{risk_areas}} or crucial user journeys).\nTest Environment & Data: Note any requirements for the test environment or data setup (e.g., staging configurations, test data) to simulate real-world conditions and edge cases.\nResponsibilities: If multiple people are involved, outline who will conduct which tests (developers, QA, etc.) and any review or sign-off procedures for quality.\nExit Criteria: Define clear criteria for testing completion and release readiness (e.g., all critical tests passed, no Severity-1 bugs open, performance benchmarks met).\nEnsure the test plan is organised and considers both obvious and non-obvious scenarios. Include how {{feature_description}} interacts with existing systems so we catch any integration or regression issues before release.",
                    "variables": ["feature_description", "risk_areas"],
                    "rating": 4.8,
                    "usageCount": 0
                },
                {
                    "id": "chaos-day-experiment-designer",
                    "title": "Chaos-Day Experiment Designer",
                    "description": "Plan a safe-to-fail fault-injection day to reveal resilience gaps.",
                    "complexity": "high",
                    "timeEstimate": "45-60 mins",
                    "roles": ["DevOps Engineer", "QA Lead", "Engineering Lead"],
                    "tags": ["Chaos Engineering", "Resilience", "Reliability"],
                    "prompt": "Outline a one-day schedule to inject three controlled failures into {{service_name}} (e.g., node termination, latency spike, dependency outage). For each experiment: a) hypothesis, b) blast radius & rollback plan, c) expected observable signals, d) success criteria, e) learning capture method.",
                    "variables": ["service_name"],
                    "rating": 0,
                    "usageCount": 0
                },
                {
                    "id": "triz-innovative-solution-evaluator",
                    "title": "TRIZ Innovative Solution Evaluator",
                    "description": "Apply TRIZ principles to resolve contradictions without compromise.",
                    "complexity": "high",
                    "timeEstimate": "45-60 mins",
                    "roles": ["Engineering Lead", "Product Manager"],
                    "tags": ["TRIZ", "Inventive Problem Solving"],
                    "prompt": "Identify the main technical contradiction in {{technical_problem}}. Map it to TRIZ parameters and list at least three relevant inventive principles. Generate one concept per principle and rate each for feasibility, impact, and novelty. Select the top concept to prototype.",
                    "variables": ["technical_problem"],
                    "rating": 0,
                    "usageCount": 0
                }
            ]
        },
        {
            "id": "measure",
            "name": "Measure & Learn",
            "description": "Assess performance and extract insights for continuous improvement",
            "color": "#fc8181",
            "icon": '<i data-feather="trending-up" style="color: #ff0000; stroke-width: 1.5px;"></i>',
            "prompts": [
                {
                    "id": "customer-impact",
                    "title": "Customer Impact Assessor",
                    "description": "Measure customer value delivery and satisfaction outcomes",
                    "complexity": "medium",
                    "timeEstimate": "30-40 mins",
                    "roles": ["Product Manager", "UX Designer"],
                    "tags": ["Customer", "Impact", "Value"],
                    "prompt": "Assess customer impact of {{delivered_feature}} by analysing: usage patterns, satisfaction scores, support ticket trends, customer feedback themes, and health outcome indicators. Identify opportunities to enhance customer value in future iterations.",
                    "variables": ["delivered_feature"],
                    "rating": 4.7,
                    "usageCount": 142
                },
                {
                    "id": "retrospective-insight-generator",
                    "title": "Retrospective Insight Generator",
                    "description": "Use in the measure & learn phase after a sprint or project to facilitate a retrospective",
                    "complexity": "medium",
                    "timeEstimate": "20-30 mins",
                    "roles": ["Scrum Master", "Squad Lead"],
                    "tags": ["Retrospective", "Continuous Improvement", "Team Reflection"],
                    "prompt": "I'm preparing a retrospective for {{team_project_name}} covering {{time_frame}}. I want to spark deep reflection and continuous improvement. Given our focus on {{focus_topics}}, please suggest a set of retrospective prompts organised by theme. For example:\nAchievements: Questions about what went well and why (e.g., \"What were our major wins in {{time_frame}} and what practices helped achieve them?\").\nChallenges: Questions to uncover issues and root causes (e.g., \"Which goals did we miss and what were the underlying reasons?\", \"What blockers or pain points kept coming up?\").\nTeam Process: Questions about how we worked together (e.g., \"How effective was our communication and planning?\", \"Where did our process shine, and where did it slow us down?\").\nExternal Factors: Questions about outside influences (e.g., \"How did external dependencies or changes impact us?\", \"Did we encounter any surprises from the market or customers?\").\nIdeas for Improvement: Questions to brainstorm actionable changes (e.g., \"What is one thing we should start, stop, or continue doing next?\", \"What experiment can we try to address a key challenge?\").\nProvide 2-3 questions under each theme. The questions should encourage honest dialogue and analysis of patterns, not just isolated incidents. The goal is to help the team examine {{time_frame}} holistically and leave the retrospective with clear action items for improvement.",
                    "variables": ["team_project_name", "time_frame", "focus_topics"],
                    "rating": 4.7,
                    "usageCount": 0
                },
                {
                    "id": "metrics-insights-review",
                    "title": "Metrics and Insights Review",
                    "description": "Use in the measure & learn phase to analyze product or feature performance data after release",
                    "complexity": "medium",
                    "timeEstimate": "25-35 mins",
                    "roles": ["Product Manager", "Business Analyst", "Squad Lead"],
                    "tags": ["Metrics", "Analysis", "Performance Review"],
                    "prompt": "We recently gathered performance data for {{initiative_name}}. Key metrics and their values are: {{metrics_data}} (targets or benchmarks were {{targets}}). Help me analyse these results critically:\nPerformance vs. Targets: For each metric, state whether we met, exceeded, or fell short of the target – and by how much.\nPotential Causes: Discuss possible reasons behind each metric's outcome. Consider factors like user behaviour, product changes, marketing efforts, or external events that could explain the results. Highlight any unexpected findings.\nValidate Assumptions: Identify any assumptions or hypotheses we had that these results confirm or challenge.\nInsights: Highlight key learnings or patterns from the data. What do these metrics tell us about user needs, product performance, or market fit? Note any trends or surprises that stand out.\nRecommendations: Propose actions or decisions based on these insights. For example, changes to the product, areas to investigate further, or new experiments to run in the next cycle.\nOrganise the analysis by metric or theme for clarity. Ensure the insights tie back to our goals for {{initiative_name}} and include clear rationale for each recommendation, so we turn data into actionable improvements.",
                    "variables": ["initiative_name", "metrics_data", "targets"],
                    "rating": 4.7,
                    "usageCount": 0
                },
                {
                    "id": "lessons-learned-lifecycle-mapper",
                    "title": "Lessons-Learned Lifecycle Mapper",
                    "description": "Turn isolated 'aha' moments into enterprise knowledge assets.",
                    "complexity": "medium",
                    "timeEstimate": "30-40 mins",
                    "roles": ["Scrum Master", "QA Lead", "Product Manager"],
                    "tags": ["Continuous Improvement", "Knowledge Management"],
                    "prompt": "Document one recent lesson from {{project_name}}. Place it on a four-quadrant matrix (Known/Unknown × Importance). If in Unknown-Important, draft a test plan; if Known-Important, embed in standards; if Unknown-Unimportant, schedule discovery; if Known-Unimportant, archive. Record owner, due date, and follow-up check.",
                    "variables": ["project_name"],
                    "rating": 0,
                    "usageCount": 0
                },
                {
                    "id": "counterfactual-postmortem-explorer",
                    "title": "Counterfactual Post-Mortem Explorer",
                    "description": "Reveal hidden leverage by simulating alternative histories.",
                    "complexity": "high",
                    "timeEstimate": "35-45 mins",
                    "roles": ["Squad Lead", "Business Analyst", "Scrum Master"],
                    "tags": ["Counterfactuals", "Root-Cause Analysis", "Decision Quality"],
                    "prompt": "Select a missed KPI for {{initiative_name}}. Ask 'what if' we had taken a different decision at each key fork? Map at least two alternate paths and estimate their outcomes. Identify one systemic root cause and one policy change to prevent recurrence.",
                    "variables": ["initiative_name"],
                    "rating": 0,
                    "usageCount": 0
                }
            ]
        }
    ],
    "roles": ["Squad Lead", "Product Manager", "Engineering Lead", "UX Designer", "Business Analyst", "QA Lead", "Scrum Master", "DevOps Engineer", "Hub Lead", "Enterprise Architect"],
    "complexityLevels": ["low", "medium", "high"],
    "totalPrompts": 36,
    "totalUsers": 1247,
    "avgRating": 4.7
}; 